name: common CICD 
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      app_type:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  ci: # job-name
    runs-on: self-hosted ##
    outputs: # this is will use to take the jobs output
      appVersion: ${{ steps.package-version.outputs.version}}
      
    steps:
      - name: checkout the code
        uses: actions/checkout@v5

      - name: check the files
        run: ls -l

      - name: print the inputs        
        run: echo "Project ${{ inputs.project }}"

      - name: get the App Version 
        id: package-version
        run: echo "Version=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"

      - name: Print the version 
        run: echo ${{ steps.package-version.outputs.version}}

      - name: install dependies
        run: npm install

      - name: build docker image
        run: docker build -t 352742379477.dkr.ecr.us-east-1.amazonaws.com/${{inputs.project }}/${{ inputs.component }}:${{ steps.package-version.outputs.version}} .