name: common CICD 
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      app_type:
        required: true
        type: string
jobs:
  ci: # job-name
    runs-on: self-hosted ##
    outputs: # this is will use to take the jobs output
      appVersion: ${{ steps.package-version.outputs.version}}
      
    steps:
      - name: checkout the code
        uses: actions/checkout@v5
      - name: check the files
        run: ls -l
      - name: print the inputs
        run: echo "Project ${{ inputs.project }}"
      - name: get the App Version 
        run: echo "Version=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"
      - name: Print the version 
        run: echo ${{ steps.package-version.outputs.version}}